### ISSUE TITLE
input description for uncertain test R code is possibly incorrect

### ISSUE THREAD

**Issue by avallecam** [LarremoreLab/bayesian-joint-prev-se-sp#1]
The description for argument `n` for the script written here is possibly incorrect. 

https://github.com/LarremoreLab/bayesian-joint-prev-se-sp/blob/7c2bae286169a507d684d17d5c9e2ad322366f15/singleSERO_uncertainTEST.R#L4

https://github.com/LarremoreLab/bayesian-joint-prev-se-sp/blob/7c2bae286169a507d684d17d5c9e2ad322366f15/singleSERO_uncertainTEST.R#L18

It may refer to the __number of total test in pop__, rather than the number of negative test. This would match with `N_{field}` at Eq.3 from [paper](https://www.biorxiv.org/content/10.1101/2020.05.23.112649v1).

Please, refer to the issue filled in the `covid_serological_sampling` repository for more details and a reprex on the same codelines:

https://github.com/LarremoreLab/covid_serological_sampling/issues/1#issue-689548717

**Comment by dblarremore** [comment]
I agree! Thank you for pointing this out. Corrected via https://github.com/LarremoreLab/bayesian-joint-prev-se-sp/commit/9970535d3562bded49b94c149448c38b2b3ece37 and closed.
